// ARQUIVO GERADO — não editar à mão.
// Origem: https://api.tibiadata.com/v4/creatures (TibiaData 4.10.0)
// Gerado em: 2026-09-16
// Regerar:  node --experimental-strip-types scripts/atualizar-criaturas.ts
//
// Tupla [nome, race, url do sprite]. Tupla e não objeto para o arquivo não
// triplicar de tamanho com nomes de campo repetidos 718 vezes.

export type CriaturaSprite = readonly [nome: string, race: string, imagem: string];

export const CRIATURAS: readonly CriaturaSprite[] = [
  ["Acid Blobs", "acidblob", "https://static.tibia.com/images/library/acidblob.gif"],
  ["Acolytes Of The Cult", "cultacolyte", "https://static.tibia.com/images/library/cultacolyte.gif"],
  ["Adepts Of The Cult", "cultadept", "https://static.tibia.com/images/library/cultadept.gif"],
  ["Adult Goannas", "adultgoanna", "https://static.tibia.com/images/library/adultgoanna.gif"],
  ["Afflicted Striders", "afflictedstrider", "https://static.tibia.com/images/library/afflictedstrider.gif"],
  ["Amazons", "amazon", "https://static.tibia.com/images/library/amazon.gif"],
  ["Ancient Scarabs", "ancientscarab", "https://static.tibia.com/images/library/ancientscarab.gif"],
  ["Angry Sugar Fairies", "angrysugarfairy", "https://static.tibia.com/images/library/angrysugarfairy.gif"],
  ["Animated Feathers", "animatedfeather", "https://static.tibia.com/images/library/animatedfeather.gif"],
  ["Arachnophobicas", "arachnophobica", "https://static.tibia.com/images/library/arachnophobica.gif"],
  ["Arctic Fauns", "arcticfaun", "https://static.tibia.com/images/library/arcticfaun.gif"],
  ["Armadiles", "armadile", "https://static.tibia.com/images/library/armadile.gif"],
  ["Assassins", "assassin", "https://static.tibia.com/images/library/assassin.gif"],
  ["Azure Frogs", "frogazure", "https://static.tibia.com/images/library/frogazure.gif"],
  ["Badgers", "badger", "https://static.tibia.com/images/library/badger.gif"],
  ["Bandits", "bandit", "https://static.tibia.com/images/library/bandit.gif"],
  ["Banshees", "banshee", "https://static.tibia.com/images/library/banshee.gif"],
  ["Barbarian Bloodwalkers", "barbarianbloodwalker", "https://static.tibia.com/images/library/barbarianbloodwalker.gif"],
  ["Barbarian Brutetamers", "barbarianbrutetamer", "https://static.tibia.com/images/library/barbarianbrutetamer.gif"],
  ["Barbarian Headsplitters", "barbarianheadsplitter", "https://static.tibia.com/images/library/barbarianheadsplitter.gif"],
  ["Barbarian Skullhunters", "barbarianskullhunter", "https://static.tibia.com/images/library/barbarianskullhunter.gif"],
  ["Barkless Devotees", "barklessdevotee", "https://static.tibia.com/images/library/barklessdevotee.gif"],
  ["Barkless Fanatics", "barklessfanatic", "https://static.tibia.com/images/library/barklessfanatic.gif"],
  ["Bashmus", "bashmu", "https://static.tibia.com/images/library/bashmu.gif"],
  ["Bats", "bat", "https://static.tibia.com/images/library/bat.gif"],
  ["Bears", "bear", "https://static.tibia.com/images/library/bear.gif"],
  ["Behemoths", "behemoth", "https://static.tibia.com/images/library/behemoth.gif"],
  ["Betrayed Wraiths", "wraith", "https://static.tibia.com/images/library/wraith.gif"],
  ["Biting Books", "bitingbook", "https://static.tibia.com/images/library/bitingbook.gif"],
  ["Black Knights", "blackknight", "https://static.tibia.com/images/library/blackknight.gif"],
  ["Black Sphinx Acolytes", "blacksphinxacolyte", "https://static.tibia.com/images/library/blacksphinxacolyte.gif"],
  ["Blemished Spawns", "blemishedspawn", "https://static.tibia.com/images/library/blemishedspawn.gif"],
  ["Blightwalkers", "blightwalker", "https://static.tibia.com/images/library/blightwalker.gif"],
  ["Bloated Man-maggots", "bloatedmanmaggot", "https://static.tibia.com/images/library/bloatedmanmaggot.gif"],
  ["Blood Beasts", "bloodbeast", "https://static.tibia.com/images/library/bloodbeast.gif"],
  ["Blood Crabs", "bloodcrab", "https://static.tibia.com/images/library/bloodcrab.gif"],
  ["Blood Hands", "bloodhand", "https://static.tibia.com/images/library/bloodhand.gif"],
  ["Blood Priests", "bloodpriest", "https://static.tibia.com/images/library/bloodpriest.gif"],
  ["Blue Djinns", "bluedjinn", "https://static.tibia.com/images/library/bluedjinn.gif"],
  ["Bluebeaks", "bluebeak", "https://static.tibia.com/images/library/bluebeak.gif"],
  ["Boar Men", "boarman", "https://static.tibia.com/images/library/boarman.gif"],
  ["Boars", "boar", "https://static.tibia.com/images/library/boar.gif"],
  ["Bog Frogs", "bogfrog", "https://static.tibia.com/images/library/bogfrog.gif"],
  ["Bog Raiders", "bograider", "https://static.tibia.com/images/library/bograider.gif"],
  ["Bonebeasts", "bonebeast", "https://static.tibia.com/images/library/bonebeast.gif"],
  ["Bonelords", "bonelord", "https://static.tibia.com/images/library/bonelord.gif"],
  ["Bony Sea Devils", "bonyseadevil", "https://static.tibia.com/images/library/bonyseadevil.gif"],
  ["Boogies", "boogy", "https://static.tibia.com/images/library/boogy.gif"],
  ["Brachiodemons", "brachiodemon", "https://static.tibia.com/images/library/brachiodemon.gif"],
  ["Brain Squids", "brainsquid", "https://static.tibia.com/images/library/brainsquid.gif"],
  ["Braindeaths", "braindeath", "https://static.tibia.com/images/library/braindeath.gif"],
  ["Bramble Wyrmlings", "bramblewyrmling", "https://static.tibia.com/images/library/bramblewyrmling.gif"],
  ["Branchy Crawlers", "ghostlycrawler", "https://static.tibia.com/images/library/ghostlycrawler.gif"],
  ["Breach Broods", "breachbrood", "https://static.tibia.com/images/library/breachbrood.gif"],
  ["Brimstone Bugs", "brimstonebug", "https://static.tibia.com/images/library/brimstonebug.gif"],
  ["Brinebrute Inferniarches", "brinebruteinferniarch", "https://static.tibia.com/images/library/brinebruteinferniarch.gif"],
  ["Broken Shapers", "degeneratedshaper", "https://static.tibia.com/images/library/degeneratedshaper.gif"],
  ["Broodrider Inferniarches", "broodriderinferniarch", "https://static.tibia.com/images/library/broodriderinferniarch.gif"],
  ["Bugs", "bug", "https://static.tibia.com/images/library/bug.gif"],
  ["Bulltaur Alchemists", "bulltauralchemist", "https://static.tibia.com/images/library/bulltauralchemist.gif"],
  ["Bulltaur Brutes", "bulltaurbrute", "https://static.tibia.com/images/library/bulltaurbrute.gif"],
  ["Bulltaur Forgepriests", "bulltaurforgepriest", "https://static.tibia.com/images/library/bulltaurforgepriest.gif"],
  ["Burning Books", "burningcursedbook", "https://static.tibia.com/images/library/burningcursedbook.gif"],
  ["Burning Gladiators", "burninggladiator", "https://static.tibia.com/images/library/burninggladiator.gif"],
  ["Burster Spectres", "bursterspectre", "https://static.tibia.com/images/library/bursterspectre.gif"],
  ["Butterflies", "butterflypurple", "https://static.tibia.com/images/library/butterflypurple.gif"],
  ["Calamaries", "calamary", "https://static.tibia.com/images/library/calamary.gif"],
  ["Candy Floss Elementals", "candyflosselemental", "https://static.tibia.com/images/library/candyflosselemental.gif"],
  ["Candy Horrors", "candyhorror", "https://static.tibia.com/images/library/candyhorror.gif"],
  ["Capricious Phantoms", "capriciousphantom", "https://static.tibia.com/images/library/capriciousphantom.gif"],
  ["Carniphilas", "carniphila", "https://static.tibia.com/images/library/carniphila.gif"],
  ["Carnisylvan Saplings", "carnisylvansapling", "https://static.tibia.com/images/library/carnisylvansapling.gif"],
  ["Carnivostriches", "carnivostrich", "https://static.tibia.com/images/library/carnivostrich.gif"],
  ["Carrion Worms", "carrionworm", "https://static.tibia.com/images/library/carrionworm.gif"],
  ["Cats", "cat", "https://static.tibia.com/images/library/cat.gif"],
  ["Cave Chimeras", "cavechimera", "https://static.tibia.com/images/library/cavechimera.gif"],
  ["Cave Devourers", "cavedevourer", "https://static.tibia.com/images/library/cavedevourer.gif"],
  ["Cave Rats", "caverat", "https://static.tibia.com/images/library/caverat.gif"],
  ["Centipedes", "centipede", "https://static.tibia.com/images/library/centipede.gif"],
  ["Chakoya Toolshapers", "chakoyatoolshaper", "https://static.tibia.com/images/library/chakoyatoolshaper.gif"],
  ["Chakoya Tribewardens", "chakoyatribewarden", "https://static.tibia.com/images/library/chakoyatribewarden.gif"],
  ["Chakoya Windcallers", "chakoyawindcaller", "https://static.tibia.com/images/library/chakoyawindcaller.gif"],
  ["Chasm Spawns", "chasmspawn", "https://static.tibia.com/images/library/chasmspawn.gif"],
  ["Chickens", "chicken", "https://static.tibia.com/images/library/chicken.gif"],
  ["Chocolate Blobs", "chocolateblob", "https://static.tibia.com/images/library/chocolateblob.gif"],
  ["Choking Fears", "chokingfear", "https://static.tibia.com/images/library/chokingfear.gif"],
  ["Cinder Wyrmlings", "cinderwyrmling", "https://static.tibia.com/images/library/cinderwyrmling.gif"],
  ["Clay Guardians", "clayguardian", "https://static.tibia.com/images/library/clayguardian.gif"],
  ["Cliff Striders", "cliffstrider", "https://static.tibia.com/images/library/cliffstrider.gif"],
  ["Cloaks Of Terror", "cloakofterror", "https://static.tibia.com/images/library/cloakofterror.gif"],
  ["Clomps", "clomp", "https://static.tibia.com/images/library/clomp.gif"],
  ["Cobra Assassins", "cobraassassin", "https://static.tibia.com/images/library/cobraassassin.gif"],
  ["Cobra Scouts", "cobrascout", "https://static.tibia.com/images/library/cobrascout.gif"],
  ["Cobra Viziers", "cobravizier", "https://static.tibia.com/images/library/cobravizier.gif"],
  ["Cobras", "cobra", "https://static.tibia.com/images/library/cobra.gif"],
  ["Converters", "converter", "https://static.tibia.com/images/library/converter.gif"],
  ["Corym Charlatans", "charlatan", "https://static.tibia.com/images/library/charlatan.gif"],
  ["Corym Skirmishers", "skirmisher", "https://static.tibia.com/images/library/skirmisher.gif"],
  ["Corym Vanguards", "vanguard", "https://static.tibia.com/images/library/vanguard.gif"],
  ["Courage Leeches", "courageleech", "https://static.tibia.com/images/library/courageleech.gif"],
  ["Crabs", "crab", "https://static.tibia.com/images/library/crab.gif"],
  ["Crape Men", "crapeman", "https://static.tibia.com/images/library/crapeman.gif"],
  ["Crawlers", "crawler", "https://static.tibia.com/images/library/crawler.gif"],
  ["Crazed Beggars", "crazedbeggar", "https://static.tibia.com/images/library/crazedbeggar.gif"],
  ["Crazed Summer Rearguards", "crazedsummerrearguard", "https://static.tibia.com/images/library/crazedsummerrearguard.gif"],
  ["Crazed Summer Vanguards", "crazedsummervanguard", "https://static.tibia.com/images/library/crazedsummervanguard.gif"],
  ["Crazed Winter Rearguards", "crazedwinterrearguard", "https://static.tibia.com/images/library/crazedwinterrearguard.gif"],
  ["Crazed Winter Vanguards", "crazedwintervanguard", "https://static.tibia.com/images/library/crazedwintervanguard.gif"],
  ["Cream Blobs", "creamblob", "https://static.tibia.com/images/library/creamblob.gif"],
  ["Creepy Crawlers", "creepycrawler", "https://static.tibia.com/images/library/creepycrawler.gif"],
  ["Crocodiles", "crocodile", "https://static.tibia.com/images/library/crocodile.gif"],
  ["Crusaders", "crusader", "https://static.tibia.com/images/library/crusader.gif"],
  ["Crustaceae Giganticae", "crustaceagigantica", "https://static.tibia.com/images/library/crustaceagigantica.gif"],
  ["Crypt Constructs", "cryptconstruct", "https://static.tibia.com/images/library/cryptconstruct.gif"],
  ["Crypt Defilers", "cryptdefiler", "https://static.tibia.com/images/library/cryptdefiler.gif"],
  ["Crypt Fiends", "cryptfiend", "https://static.tibia.com/images/library/cryptfiend.gif"],
  ["Crypt Mages", "cryptmage", "https://static.tibia.com/images/library/cryptmage.gif"],
  ["Crypt Shamblers", "cryptshambler", "https://static.tibia.com/images/library/cryptshambler.gif"],
  ["Crypt Wardens", "cryptwarden", "https://static.tibia.com/images/library/cryptwarden.gif"],
  ["Crypt Warriors", "cryptwarrior", "https://static.tibia.com/images/library/cryptwarrior.gif"],
  ["Crystal Spiders", "crystalspider", "https://static.tibia.com/images/library/crystalspider.gif"],
  ["Crystalcrushers", "crystalcrusher", "https://static.tibia.com/images/library/crystalcrusher.gif"],
  ["Cult Believers", "cultbeliever", "https://static.tibia.com/images/library/cultbeliever.gif"],
  ["Cult Enforcers", "cultenforcer", "https://static.tibia.com/images/library/cultenforcer.gif"],
  ["Cult Scholars", "cultscholar", "https://static.tibia.com/images/library/cultscholar.gif"],
  ["Cunning Werepanthers", "cunningwerepanther", "https://static.tibia.com/images/library/cunningwerepanther.gif"],
  ["Cursed Apes", "cursedape", "https://static.tibia.com/images/library/cursedape.gif"],
  ["Cursed Books", "cursedbook", "https://static.tibia.com/images/library/cursedbook.gif"],
  ["Cursed Prospectors", "cursedprospector", "https://static.tibia.com/images/library/cursedprospector.gif"],
  ["Cyclopes", "cyclops", "https://static.tibia.com/images/library/cyclops.gif"],
  ["Cyclopes Drone", "cyclopsdrone", "https://static.tibia.com/images/library/cyclopsdrone.gif"],
  ["Cyclopes Smith", "cyclopssmith", "https://static.tibia.com/images/library/cyclopssmith.gif"],
  ["Cyclursuses", "cyclursus", "https://static.tibia.com/images/library/cyclursus.gif"],
  ["Dark Apprentices", "darkapprentice", "https://static.tibia.com/images/library/darkapprentice.gif"],
  ["Dark Carnisylvans", "carnisylvandark", "https://static.tibia.com/images/library/carnisylvandark.gif"],
  ["Dark Fauns", "darkfaun", "https://static.tibia.com/images/library/darkfaun.gif"],
  ["Dark Magicians", "darkmagician", "https://static.tibia.com/images/library/darkmagician.gif"],
  ["Dark Monks", "darkmonk", "https://static.tibia.com/images/library/darkmonk.gif"],
  ["Dark Torturers", "darktorturer", "https://static.tibia.com/images/library/darktorturer.gif"],
  ["Darklight Constructs", "darklightconstruct", "https://static.tibia.com/images/library/darklightconstruct.gif"],
  ["Darklight Emitters", "darklightemitter", "https://static.tibia.com/images/library/darklightemitter.gif"],
  ["Darklight Matters", "darklightmatter", "https://static.tibia.com/images/library/darklightmatter.gif"],
  ["Darklight Sources", "darklightsource", "https://static.tibia.com/images/library/darklightsource.gif"],
  ["Darklight Strikers", "darklightstriker", "https://static.tibia.com/images/library/darklightstriker.gif"],
  ["Dawnfire Asuras", "asura", "https://static.tibia.com/images/library/asura.gif"],
  ["Death Blobs", "deathblob", "https://static.tibia.com/images/library/deathblob.gif"],
  ["Deathling Scouts", "deathlingscout", "https://static.tibia.com/images/library/deathlingscout.gif"],
  ["Deathling Spellsingers", "deathlingspellsinger", "https://static.tibia.com/images/library/deathlingspellsinger.gif"],
  ["Deepling Guards", "deeplingguard", "https://static.tibia.com/images/library/deeplingguard.gif"],
  ["Deepling Scouts", "deeplingscout", "https://static.tibia.com/images/library/deeplingscout.gif"],
  ["Deepling Spellsingers", "deeplingspellsinger", "https://static.tibia.com/images/library/deeplingspellsinger.gif"],
  ["Deepling Warriors", "deeplingwarrior", "https://static.tibia.com/images/library/deeplingwarrior.gif"],
  ["Deepling Workers", "deeplingworker", "https://static.tibia.com/images/library/deeplingworker.gif"],
  ["Deepsea Blood Crabs", "bloodcrabunderwater", "https://static.tibia.com/images/library/bloodcrabunderwater.gif"],
  ["Deepworms", "deepworm", "https://static.tibia.com/images/library/deepworm.gif"],
  ["Deer", "deer", "https://static.tibia.com/images/library/deer.gif"],
  ["Defilers", "defiler", "https://static.tibia.com/images/library/defiler.gif"],
  ["Demon Outcasts", "demonoutcast", "https://static.tibia.com/images/library/demonoutcast.gif"],
  ["Demon Skeletons", "demonskeleton", "https://static.tibia.com/images/library/demonskeleton.gif"],
  ["Demons", "demon", "https://static.tibia.com/images/library/demon.gif"],
  ["Destroyers", "destroyer", "https://static.tibia.com/images/library/destroyer.gif"],
  ["Devoted Radiant Acolytes", "devotedradiantacolyte", "https://static.tibia.com/images/library/devotedradiantacolyte.gif"],
  ["Devoted Radiant Inquisitors", "devotedradiantinquisitor", "https://static.tibia.com/images/library/devotedradiantinquisitor.gif"],
  ["Devoted Radiant Paragons", "devotedradiantparagon", "https://static.tibia.com/images/library/devotedradiantparagon.gif"],
  ["Devoted Radiant Templars", "devotedradianttemplar", "https://static.tibia.com/images/library/devotedradianttemplar.gif"],
  ["Devoted Radiant Wardens", "devotedradiantwarden", "https://static.tibia.com/images/library/devotedradiantwarden.gif"],
  ["Devoted Radiant Zealots", "devotedradiantzealot", "https://static.tibia.com/images/library/devotedradiantzealot.gif"],
  ["Devourers", "devourer", "https://static.tibia.com/images/library/devourer.gif"],
  ["Diabolic Imps", "diabolicimp", "https://static.tibia.com/images/library/diabolicimp.gif"],
  ["Diamond Servant Replicas", "replicadiamondservant", "https://static.tibia.com/images/library/replicadiamondservant.gif"],
  ["Diamond Servants", "diamondservant", "https://static.tibia.com/images/library/diamondservant.gif"],
  ["Diremaws", "diremaw", "https://static.tibia.com/images/library/diremaw.gif"],
  ["Distorted Phantoms", "distortedphantom", "https://static.tibia.com/images/library/distortedphantom.gif"],
  ["Dogs", "dog", "https://static.tibia.com/images/library/dog.gif"],
  ["Dragolisks", "dragolisk", "https://static.tibia.com/images/library/dragolisk.gif"],
  ["Dragon Hatchlings", "dragonhatchling", "https://static.tibia.com/images/library/dragonhatchling.gif"],
  ["Dragon Lord Hatchlings", "dragonlordhatchling", "https://static.tibia.com/images/library/dragonlordhatchling.gif"],
  ["Dragon Lords", "dragonlord", "https://static.tibia.com/images/library/dragonlord.gif"],
  ["Dragonlings", "dragonling", "https://static.tibia.com/images/library/dragonling.gif"],
  ["Dragons", "dragon", "https://static.tibia.com/images/library/dragon.gif"],
  ["Draken Abominations", "drakenabomination", "https://static.tibia.com/images/library/drakenabomination.gif"],
  ["Draken Elites", "drakenelite", "https://static.tibia.com/images/library/drakenelite.gif"],
  ["Draken Spellweavers", "drakenspellweaver", "https://static.tibia.com/images/library/drakenspellweaver.gif"],
  ["Draken Warmasters", "drakenwarmaster", "https://static.tibia.com/images/library/drakenwarmaster.gif"],
  ["Draptors", "draptor", "https://static.tibia.com/images/library/draptor.gif"],
  ["Dread Intruders", "dreadintruder", "https://static.tibia.com/images/library/dreadintruder.gif"],
  ["Drillworms", "drillworm", "https://static.tibia.com/images/library/drillworm.gif"],
  ["Dromedaries", "dromedary", "https://static.tibia.com/images/library/dromedary.gif"],
  ["Druid's Apparitions", "apparitionofadruid", "https://static.tibia.com/images/library/apparitionofadruid.gif"],
  ["Dwarf Geomancers", "dwarfgeomancer", "https://static.tibia.com/images/library/dwarfgeomancer.gif"],
  ["Dwarf Guards", "dwarfguard", "https://static.tibia.com/images/library/dwarfguard.gif"],
  ["Dwarf Miners", "dwarfminer", "https://static.tibia.com/images/library/dwarfminer.gif"],
  ["Dwarf Soldiers", "dwarfsoldier", "https://static.tibia.com/images/library/dwarfsoldier.gif"],
  ["Dwarfs", "dwarf", "https://static.tibia.com/images/library/dwarf.gif"],
  ["Dworc Fleshhunters", "dworcfleshhunter", "https://static.tibia.com/images/library/dworcfleshhunter.gif"],
  ["Dworc Shadowstalkers", "norcferatudworc", "https://static.tibia.com/images/library/norcferatudworc.gif"],
  ["Dworc Venomsnipers", "dworcvenomsniper", "https://static.tibia.com/images/library/dworcvenomsniper.gif"],
  ["Dworc Voodoomasters", "dworcvoodoomaster", "https://static.tibia.com/images/library/dworcvoodoomaster.gif"],
  ["Earth Elementals", "earthelemental", "https://static.tibia.com/images/library/earthelemental.gif"],
  ["Efreet", "efreet", "https://static.tibia.com/images/library/efreet.gif"],
  ["Elder Bonelords", "elderbonelord", "https://static.tibia.com/images/library/elderbonelord.gif"],
  ["Elder Wyrms", "elderwyrm", "https://static.tibia.com/images/library/elderwyrm.gif"],
  ["Elephants", "elephant", "https://static.tibia.com/images/library/elephant.gif"],
  ["Elf Arcanists", "elfarcanist", "https://static.tibia.com/images/library/elfarcanist.gif"],
  ["Elf Scouts", "elfscout", "https://static.tibia.com/images/library/elfscout.gif"],
  ["Elves", "elf", "https://static.tibia.com/images/library/elf.gif"],
  ["Emerald Damselflies", "emeralddamselfly", "https://static.tibia.com/images/library/emeralddamselfly.gif"],
  ["Emerald Tortoises", "emeraldtortoise", "https://static.tibia.com/images/library/emeraldtortoise.gif"],
  ["Energetic Books", "energeticbook", "https://static.tibia.com/images/library/energeticbook.gif"],
  ["Energuardians Of Tales", "energuardianoftales", "https://static.tibia.com/images/library/energuardianoftales.gif"],
  ["Energy Elementals", "energyelemental", "https://static.tibia.com/images/library/energyelemental.gif"],
  ["Enfeebled Silencers", "enfeebledsilencer", "https://static.tibia.com/images/library/enfeebledsilencer.gif"],
  ["Enlighteneds Of The Cult", "cultpriest", "https://static.tibia.com/images/library/cultpriest.gif"],
  ["Enraged Crystal Golems", "crystalgolem", "https://static.tibia.com/images/library/crystalgolem.gif"],
  ["Enslaved Dwarfs", "enslaveddwarf", "https://static.tibia.com/images/library/enslaveddwarf.gif"],
  ["Eternal Guardians", "eternalguardian", "https://static.tibia.com/images/library/eternalguardian.gif"],
  ["Evil Prospectors", "evilprospector", "https://static.tibia.com/images/library/evilprospector.gif"],
  ["Execowtioners", "execowtioner", "https://static.tibia.com/images/library/execowtioner.gif"],
  ["Exotic Bats", "caribbeanbat", "https://static.tibia.com/images/library/caribbeanbat.gif"],
  ["Exotic Cave Spiders", "caribbeancavespider", "https://static.tibia.com/images/library/caribbeancavespider.gif"],
  ["Eyeless Devourers", "eyelessdevourer", "https://static.tibia.com/images/library/eyelessdevourer.gif"],
  ["Falcon Knights", "falconknight", "https://static.tibia.com/images/library/falconknight.gif"],
  ["Falcon Paladins", "falconpaladin", "https://static.tibia.com/images/library/falconpaladin.gif"],
  ["Fauns", "faun", "https://static.tibia.com/images/library/faun.gif"],
  ["Feral Sphinxes", "feralsphinx", "https://static.tibia.com/images/library/feralsphinx.gif"],
  ["Feral Werecrocodiles", "feralwerecrocodile", "https://static.tibia.com/images/library/feralwerecrocodile.gif"],
  ["Feversleeps", "feversleep", "https://static.tibia.com/images/library/feversleep.gif"],
  ["Filth Toads", "filthtoad", "https://static.tibia.com/images/library/filthtoad.gif"],
  ["Fire Devils", "firedevil", "https://static.tibia.com/images/library/firedevil.gif"],
  ["Fire Elementals", "fireelemental", "https://static.tibia.com/images/library/fireelemental.gif"],
  ["Firestarters", "firestarter", "https://static.tibia.com/images/library/firestarter.gif"],
  ["Fish", "fish", "https://static.tibia.com/images/library/fish.gif"],
  ["Flamingos", "flamingo", "https://static.tibia.com/images/library/flamingo.gif"],
  ["Flimsy Lost Souls", "lostsoulweak", "https://static.tibia.com/images/library/lostsoulweak.gif"],
  ["Floating Savants", "floatingsavant", "https://static.tibia.com/images/library/floatingsavant.gif"],
  ["Flying Books", "flyingbook", "https://static.tibia.com/images/library/flyingbook.gif"],
  ["Foam Stalkers", "foamstalker", "https://static.tibia.com/images/library/foamstalker.gif"],
  ["Forest Furies", "forestfury", "https://static.tibia.com/images/library/forestfury.gif"],
  ["Foxes", "fox", "https://static.tibia.com/images/library/fox.gif"],
  ["Frazzlemaws", "frazzlemaw", "https://static.tibia.com/images/library/frazzlemaw.gif"],
  ["Freakish Lost Souls", "lostsoulhard", "https://static.tibia.com/images/library/lostsoulhard.gif"],
  ["Frost Dragon Hatchlings", "frostdragonhatchling", "https://static.tibia.com/images/library/frostdragonhatchling.gif"],
  ["Frost Dragons", "frostdragon", "https://static.tibia.com/images/library/frostdragon.gif"],
  ["Frost Flower Asuras", "frostflowerasura", "https://static.tibia.com/images/library/frostflowerasura.gif"],
  ["Frost Giantesses", "frostgiantess", "https://static.tibia.com/images/library/frostgiantess.gif"],
  ["Frost Giants", "frostgiant", "https://static.tibia.com/images/library/frostgiant.gif"],
  ["Frost Trolls", "frosttroll", "https://static.tibia.com/images/library/frosttroll.gif"],
  ["Fruit Drops", "fruitdrop", "https://static.tibia.com/images/library/fruitdrop.gif"],
  ["Furies", "fury", "https://static.tibia.com/images/library/fury.gif"],
  ["Gang Members", "gangmember", "https://static.tibia.com/images/library/gangmember.gif"],
  ["Gargoyles", "gargoyle", "https://static.tibia.com/images/library/gargoyle.gif"],
  ["Gazer Spectres", "gazerspectre", "https://static.tibia.com/images/library/gazerspectre.gif"],
  ["Gazers", "gazer", "https://static.tibia.com/images/library/gazer.gif"],
  ["Ghastly Dragons", "ghastlydragon", "https://static.tibia.com/images/library/ghastlydragon.gif"],
  ["Ghosts", "ghost", "https://static.tibia.com/images/library/ghost.gif"],
  ["Ghouls", "ghoul", "https://static.tibia.com/images/library/ghoul.gif"],
  ["Giant Spiders", "giantspider", "https://static.tibia.com/images/library/giantspider.gif"],
  ["Gingerbread Men", "gingerbreadman", "https://static.tibia.com/images/library/gingerbreadman.gif"],
  ["Girtablilu Warriors", "girtabliluwarrior", "https://static.tibia.com/images/library/girtabliluwarrior.gif"],
  ["Gladiators", "gladiator", "https://static.tibia.com/images/library/gladiator.gif"],
  ["Gloom Maws", "batface", "https://static.tibia.com/images/library/batface.gif"],
  ["Gloom Wolves", "gloomwolf", "https://static.tibia.com/images/library/gloomwolf.gif"],
  ["Glooth Anemones", "gloothanemone", "https://static.tibia.com/images/library/gloothanemone.gif"],
  ["Glooth Bandits", "gloothbandit", "https://static.tibia.com/images/library/gloothbandit.gif"],
  ["Glooth Blobs", "gloothblob", "https://static.tibia.com/images/library/gloothblob.gif"],
  ["Glooth Brigands", "gloothbrigand", "https://static.tibia.com/images/library/gloothbrigand.gif"],
  ["Glooth Golems", "gloothgolem", "https://static.tibia.com/images/library/gloothgolem.gif"],
  ["Gnarlhounds", "gnarlhound", "https://static.tibia.com/images/library/gnarlhound.gif"],
  ["Goblin Assassins", "goblinassassin", "https://static.tibia.com/images/library/goblinassassin.gif"],
  ["Goblin Scavengers", "goblinscavenger", "https://static.tibia.com/images/library/goblinscavenger.gif"],
  ["Goblins", "goblin", "https://static.tibia.com/images/library/goblin.gif"],
  ["Goggle Cakes", "gogglecake", "https://static.tibia.com/images/library/gogglecake.gif"],
  ["Golden Servant Replicas", "replicagoldenservant", "https://static.tibia.com/images/library/replicagoldenservant.gif"],
  ["Golden Servants", "goldenservant", "https://static.tibia.com/images/library/goldenservant.gif"],
  ["Gore Horns", "gorehorn", "https://static.tibia.com/images/library/gorehorn.gif"],
  ["Gorerillas", "gorerilla", "https://static.tibia.com/images/library/gorerilla.gif"],
  ["Gorger Inferniarches", "gorgerinferniarch", "https://static.tibia.com/images/library/gorgerinferniarch.gif"],
  ["Gozzlers", "gozzler", "https://static.tibia.com/images/library/gozzler.gif"],
  ["Grave Robbers", "graverobber", "https://static.tibia.com/images/library/graverobber.gif"],
  ["Gravediggers", "gravedigger", "https://static.tibia.com/images/library/gravedigger.gif"],
  ["Green Djinns", "greendjinn", "https://static.tibia.com/images/library/greendjinn.gif"],
  ["Grim Reapers", "grimreaper", "https://static.tibia.com/images/library/grimreaper.gif"],
  ["Grimeleeches", "grimeleech", "https://static.tibia.com/images/library/grimeleech.gif"],
  ["Gryphons", "gryphon", "https://static.tibia.com/images/library/gryphon.gif"],
  ["Guardians Of Tales", "guardianoftales", "https://static.tibia.com/images/library/guardianoftales.gif"],
  ["Guzzlemaws", "guzzlemaw", "https://static.tibia.com/images/library/guzzlemaw.gif"],
  ["Hands Of Cursed Fate", "handofcursedfate", "https://static.tibia.com/images/library/handofcursedfate.gif"],
  ["Harpies", "harpy", "https://static.tibia.com/images/library/harpy.gif"],
  ["Haunted Hunters", "hauntedhunter", "https://static.tibia.com/images/library/hauntedhunter.gif"],
  ["Haunted Treelings", "hauntedtreeling", "https://static.tibia.com/images/library/hauntedtreeling.gif"],
  ["Hawk Hoppers", "hawkhopper", "https://static.tibia.com/images/library/hawkhopper.gif"],
  ["Headpeckers", "headpecker", "https://static.tibia.com/images/library/headpecker.gif"],
  ["Headwalkers", "headwalker", "https://static.tibia.com/images/library/headwalker.gif"],
  ["Hellfire Fighters", "hellfirefighter", "https://static.tibia.com/images/library/hellfirefighter.gif"],
  ["Hellflayers", "hellflayer", "https://static.tibia.com/images/library/hellflayer.gif"],
  ["Hellhounds", "hellhound", "https://static.tibia.com/images/library/hellhound.gif"],
  ["Hellhunter Inferniarches", "hellhunterinferniarch", "https://static.tibia.com/images/library/hellhunterinferniarch.gif"],
  ["Hellspawns", "hellspawn", "https://static.tibia.com/images/library/hellspawn.gif"],
  ["Heroes", "hero", "https://static.tibia.com/images/library/hero.gif"],
  ["Hideous Fungi", "hideousfungus", "https://static.tibia.com/images/library/hideousfungus.gif"],
  ["High Voltage Elementals", "highvoltageelemental", "https://static.tibia.com/images/library/highvoltageelemental.gif"],
  ["Honey Elementals", "honeyelemental", "https://static.tibia.com/images/library/honeyelemental.gif"],
  ["Hulking Carnisylvans", "carnisylvanhulking", "https://static.tibia.com/images/library/carnisylvanhulking.gif"],
  ["Hulking Prehemoths", "hulkingprehemoth", "https://static.tibia.com/images/library/hulkingprehemoth.gif"],
  ["Humongous Fungi", "humongousfungus", "https://static.tibia.com/images/library/humongousfungus.gif"],
  ["Hunters", "hunter", "https://static.tibia.com/images/library/hunter.gif"],
  ["Huskies", "husky", "https://static.tibia.com/images/library/husky.gif"],
  ["Hyaenas", "hyaena", "https://static.tibia.com/images/library/hyaena.gif"],
  ["Hydras", "hydra", "https://static.tibia.com/images/library/hydra.gif"],
  ["Ice Golems", "icegolem", "https://static.tibia.com/images/library/icegolem.gif"],
  ["Ice Witches", "icewitch", "https://static.tibia.com/images/library/icewitch.gif"],
  ["Icecold Books", "icecoldbook", "https://static.tibia.com/images/library/icecoldbook.gif"],
  ["Iceplume Striders", "iceplumestrider", "https://static.tibia.com/images/library/iceplumestrider.gif"],
  ["Iks Aucars", "iksaucar", "https://static.tibia.com/images/library/iksaucar.gif"],
  ["Iks Chukas", "ikschuka", "https://static.tibia.com/images/library/ikschuka.gif"],
  ["Iks Pututus", "ikspututu", "https://static.tibia.com/images/library/ikspututu.gif"],
  ["Iks Yapunacs", "iksyapunac", "https://static.tibia.com/images/library/iksyapunac.gif"],
  ["Imperials", "imperial", "https://static.tibia.com/images/library/imperial.gif"],
  ["Infernal Demons", "infernaldemon", "https://static.tibia.com/images/library/infernaldemon.gif"],
  ["Infernal Phantoms", "infernalphantom", "https://static.tibia.com/images/library/infernalphantom.gif"],
  ["Infernalists", "infernalist", "https://static.tibia.com/images/library/infernalist.gif"],
  ["Infernoid Blobs", "infernoidblob", "https://static.tibia.com/images/library/infernoidblob.gif"],
  ["Infernoid Hounds", "infernoidhound", "https://static.tibia.com/images/library/infernoidhound.gif"],
  ["Infernoid Souls", "infernoidsoul", "https://static.tibia.com/images/library/infernoidsoul.gif"],
  ["Infernoid Spirituals", "infernoidspiritual", "https://static.tibia.com/images/library/infernoidspiritual.gif"],
  ["Ink Blobs", "inkblob", "https://static.tibia.com/images/library/inkblob.gif"],
  ["Insane Sirens", "insanesiren", "https://static.tibia.com/images/library/insanesiren.gif"],
  ["Insect Swarms", "insectswarm", "https://static.tibia.com/images/library/insectswarm.gif"],
  ["Insectoid Scouts", "insectoidscout", "https://static.tibia.com/images/library/insectoidscout.gif"],
  ["Insectoid Workers", "insectoidworker", "https://static.tibia.com/images/library/insectoidworker.gif"],
  ["Instable Breach Broods", "instablebreachbrood", "https://static.tibia.com/images/library/instablebreachbrood.gif"],
  ["Instable Sparkions", "instablesparkion", "https://static.tibia.com/images/library/instablesparkion.gif"],
  ["Iron Servant Replicas", "replicaironservant", "https://static.tibia.com/images/library/replicaironservant.gif"],
  ["Iron Servants", "ironservant", "https://static.tibia.com/images/library/ironservant.gif"],
  ["Ironblights", "ironblight", "https://static.tibia.com/images/library/ironblight.gif"],
  ["Island Trolls", "islandtroll", "https://static.tibia.com/images/library/islandtroll.gif"],
  ["Jaracals", "jaracal", "https://static.tibia.com/images/library/jaracal.gif"],
  ["Jellyfish", "jellyfish", "https://static.tibia.com/images/library/jellyfish.gif"],
  ["Juggernauts", "juggernaut", "https://static.tibia.com/images/library/juggernaut.gif"],
  ["Jungle Moas", "junglemoa", "https://static.tibia.com/images/library/junglemoa.gif"],
  ["Juvenile Bashmus", "juvenilebashmu", "https://static.tibia.com/images/library/juvenilebashmu.gif"],
  ["Killer Caimans", "killercaiman", "https://static.tibia.com/images/library/killercaiman.gif"],
  ["Knight's Apparitions", "knightsapparition", "https://static.tibia.com/images/library/knightsapparition.gif"],
  ["Knowledge Elementals", "knowledgeelemental", "https://static.tibia.com/images/library/knowledgeelemental.gif"],
  ["Kollos", "kollos", "https://static.tibia.com/images/library/kollos.gif"],
  ["Kongras", "kongra", "https://static.tibia.com/images/library/kongra.gif"],
  ["Ladybugs", "ladybug", "https://static.tibia.com/images/library/ladybug.gif"],
  ["Lamassus", "lamassu", "https://static.tibia.com/images/library/lamassu.gif"],
  ["Lancer Beetles", "lancerbeetle", "https://static.tibia.com/images/library/lancerbeetle.gif"],
  ["Larvas", "larva", "https://static.tibia.com/images/library/larva.gif"],
  ["Lava Golems", "lavagolem", "https://static.tibia.com/images/library/lavagolem.gif"],
  ["Lava Lurkers", "lavablob", "https://static.tibia.com/images/library/lavablob.gif"],
  ["Lavafungi", "lavafungus", "https://static.tibia.com/images/library/lavafungus.gif"],
  ["Lavaworms", "lavaworm", "https://static.tibia.com/images/library/lavaworm.gif"],
  ["Leaf Golems", "leafgolem", "https://static.tibia.com/images/library/leafgolem.gif"],
  ["Liches", "lich", "https://static.tibia.com/images/library/lich.gif"],
  ["Liodiles", "liodileman", "https://static.tibia.com/images/library/liodileman.gif"],
  ["Lion Hydras", "lionhydra", "https://static.tibia.com/images/library/lionhydra.gif"],
  ["Lions", "lion", "https://static.tibia.com/images/library/lion.gif"],
  ["Lizard Chosens", "lizardchosen", "https://static.tibia.com/images/library/lizardchosen.gif"],
  ["Lizard Commanders", "lizardcommander", "https://static.tibia.com/images/library/lizardcommander.gif"],
  ["Lizard Dragon Priests", "lizarddragonpriest", "https://static.tibia.com/images/library/lizarddragonpriest.gif"],
  ["Lizard Executioners", "lizardexecutioner", "https://static.tibia.com/images/library/lizardexecutioner.gif"],
  ["Lizard Henchmans", "lizardhenchman", "https://static.tibia.com/images/library/lizardhenchman.gif"],
  ["Lizard High Guards", "lizardhighguard", "https://static.tibia.com/images/library/lizardhighguard.gif"],
  ["Lizard Legionnaires", "lizardlegionnaire", "https://static.tibia.com/images/library/lizardlegionnaire.gif"],
  ["Lizard Magicians", "lizardmagician", "https://static.tibia.com/images/library/lizardmagician.gif"],
  ["Lizard Sentinels", "lizardsentinel", "https://static.tibia.com/images/library/lizardsentinel.gif"],
  ["Lizard Snakecharmers", "lizardsnakecharmer", "https://static.tibia.com/images/library/lizardsnakecharmer.gif"],
  ["Lizard Swordmasters", "lizardswordmaster", "https://static.tibia.com/images/library/lizardswordmaster.gif"],
  ["Lizard Templars", "lizardtemplar", "https://static.tibia.com/images/library/lizardtemplar.gif"],
  ["Lizard Zaoguns", "lizardzaogun", "https://static.tibia.com/images/library/lizardzaogun.gif"],
  ["Lost Bashers", "lostdwarfbasher", "https://static.tibia.com/images/library/lostdwarfbasher.gif"],
  ["Lost Berserkers", "lostberserker", "https://static.tibia.com/images/library/lostberserker.gif"],
  ["Lost Hushers", "lostdwarfhusher", "https://static.tibia.com/images/library/lostdwarfhusher.gif"],
  ["Lost Souls", "lostsoul", "https://static.tibia.com/images/library/lostsoul.gif"],
  ["Lost Throwers", "lostthrower", "https://static.tibia.com/images/library/lostthrower.gif"],
  ["Lumbering Carnivors", "lumberingcarnivor", "https://static.tibia.com/images/library/lumberingcarnivor.gif"],
  ["Mad Scientists", "madscientist", "https://static.tibia.com/images/library/madscientist.gif"],
  ["Magma Crawlers", "magmacrawler", "https://static.tibia.com/images/library/magmacrawler.gif"],
  ["Makaras", "makara", "https://static.tibia.com/images/library/makara.gif"],
  ["Mammoths", "mammoth", "https://static.tibia.com/images/library/mammoth.gif"],
  ["Manta Rays", "mantaray", "https://static.tibia.com/images/library/mantaray.gif"],
  ["Manticores", "manticore", "https://static.tibia.com/images/library/manticore.gif"],
  ["Mantosauruses", "mantosaurus", "https://static.tibia.com/images/library/mantosaurus.gif"],
  ["Many Faces", "manyfaces", "https://static.tibia.com/images/library/manyfaces.gif"],
  ["Marid", "marid", "https://static.tibia.com/images/library/marid.gif"],
  ["Marsh Stalkers", "marshstalker", "https://static.tibia.com/images/library/marshstalker.gif"],
  ["Massive Earth Elementals", "earthelementalmassive", "https://static.tibia.com/images/library/earthelementalmassive.gif"],
  ["Massive Energy Elementals", "energyelementalmassive", "https://static.tibia.com/images/library/energyelementalmassive.gif"],
  ["Massive Fire Elementals", "hellfireelemental", "https://static.tibia.com/images/library/hellfireelemental.gif"],
  ["Massive Water Elementals", "waterelementalmassive", "https://static.tibia.com/images/library/waterelementalmassive.gif"],
  ["Mean Lost Souls", "lostsoulmedium", "https://static.tibia.com/images/library/lostsoulmedium.gif"],
  ["Meandering Mushrooms", "meanderingmushroom", "https://static.tibia.com/images/library/meanderingmushroom.gif"],
  ["Medusae", "medusa", "https://static.tibia.com/images/library/medusa.gif"],
  ["Mega Dragons", "megadragon", "https://static.tibia.com/images/library/megadragon.gif"],
  ["Menacing Carnivors", "menacingcarnivor", "https://static.tibia.com/images/library/menacingcarnivor.gif"],
  ["Mercurial Menaces", "mercurialmenace", "https://static.tibia.com/images/library/mercurialmenace.gif"],
  ["Mercury Blobs", "mercuryblob", "https://static.tibia.com/images/library/mercuryblob.gif"],
  ["Merlkins", "merlkin", "https://static.tibia.com/images/library/merlkin.gif"],
  ["Metal Gargoyles", "metalgargoyle", "https://static.tibia.com/images/library/metalgargoyle.gif"],
  ["Midnight Asuras", "asuranight", "https://static.tibia.com/images/library/asuranight.gif"],
  ["Midnight Panthers", "midnightpanther", "https://static.tibia.com/images/library/midnightpanther.gif"],
  ["Minotaur Amazons", "minotauramazon", "https://static.tibia.com/images/library/minotauramazon.gif"],
  ["Minotaur Archers", "minotaurarcher", "https://static.tibia.com/images/library/minotaurarcher.gif"],
  ["Minotaur Cult Followers", "minotaurcultfollower", "https://static.tibia.com/images/library/minotaurcultfollower.gif"],
  ["Minotaur Cult Prophets", "minotaurcultprophet", "https://static.tibia.com/images/library/minotaurcultprophet.gif"],
  ["Minotaur Cult Zealots", "minotaurcultzealot", "https://static.tibia.com/images/library/minotaurcultzealot.gif"],
  ["Minotaur Guards", "minotaurguard", "https://static.tibia.com/images/library/minotaurguard.gif"],
  ["Minotaur Hunters", "minotaurhunter", "https://static.tibia.com/images/library/minotaurhunter.gif"],
  ["Minotaur Mages", "minotaurmage", "https://static.tibia.com/images/library/minotaurmage.gif"],
  ["Minotaurs", "minotaur", "https://static.tibia.com/images/library/minotaur.gif"],
  ["Mirror Images", "mirrorimage", "https://static.tibia.com/images/library/mirrorimage.gif"],
  ["Misguided Bullies", "misguidedmelee", "https://static.tibia.com/images/library/misguidedmelee.gif"],
  ["Misguided Thieves", "misguidedranged", "https://static.tibia.com/images/library/misguidedranged.gif"],
  ["Mitmah Scouts", "mitmahscout", "https://static.tibia.com/images/library/mitmahscout.gif"],
  ["Mitmah Seers", "mitmahseer", "https://static.tibia.com/images/library/mitmahseer.gif"],
  ["Monk's Apparitions", "monksapparition", "https://static.tibia.com/images/library/monksapparition.gif"],
  ["Monks", "monk", "https://static.tibia.com/images/library/monk.gif"],
  ["Monks Of The Order", "lionmonk", "https://static.tibia.com/images/library/lionmonk.gif"],
  ["Mooh'tah Warriors", "moohtahwarrior", "https://static.tibia.com/images/library/moohtahwarrior.gif"],
  ["Moohtants", "moohtant", "https://static.tibia.com/images/library/moohtant.gif"],
  ["Moonspawn Blightspitters", "moonspawnblightspitter", "https://static.tibia.com/images/library/moonspawnblightspitter.gif"],
  ["Moonspawn Oozecrowns", "moonspawnoozecrown", "https://static.tibia.com/images/library/moonspawnoozecrown.gif"],
  ["Moonstone Excavators", "moonstoneexcavator", "https://static.tibia.com/images/library/moonstoneexcavator.gif"],
  ["Moonstone Overseers", "moonstoneoverseer", "https://static.tibia.com/images/library/moonstoneoverseer.gif"],
  ["Mould Phantoms", "mouldphantom", "https://static.tibia.com/images/library/mouldphantom.gif"],
  ["Mummies", "mummy", "https://static.tibia.com/images/library/mummy.gif"],
  ["Mutated Bats", "mutatedbat", "https://static.tibia.com/images/library/mutatedbat.gif"],
  ["Mutated Humans", "mutatedhuman", "https://static.tibia.com/images/library/mutatedhuman.gif"],
  ["Mutated Rats", "mutatedrat", "https://static.tibia.com/images/library/mutatedrat.gif"],
  ["Mutated Tigers", "mutatedtiger", "https://static.tibia.com/images/library/mutatedtiger.gif"],
  ["Mycobiontic Beetles", "mycobionticbeetle", "https://static.tibia.com/images/library/mycobionticbeetle.gif"],
  ["Naga Archers", "nagaarcher", "https://static.tibia.com/images/library/nagaarcher.gif"],
  ["Naga Warriors", "nagawarrior", "https://static.tibia.com/images/library/nagawarrior.gif"],
  ["Necromancers", "necromancer", "https://static.tibia.com/images/library/necromancer.gif"],
  ["Nibblemaws", "nibblemaw", "https://static.tibia.com/images/library/nibblemaw.gif"],
  ["Night Harpies", "nightharpy", "https://static.tibia.com/images/library/nightharpy.gif"],
  ["Nightfiends", "nightfiend", "https://static.tibia.com/images/library/nightfiend.gif"],
  ["Nighthunters", "nighthunter", "https://static.tibia.com/images/library/nighthunter.gif"],
  ["Nightmare Scions", "nightmarescion", "https://static.tibia.com/images/library/nightmarescion.gif"],
  ["Nightmares", "nightmare", "https://static.tibia.com/images/library/nightmare.gif"],
  ["Nightstalkers", "nightstalker", "https://static.tibia.com/images/library/nightstalker.gif"],
  ["Noble Lions", "noblelion", "https://static.tibia.com/images/library/noblelion.gif"],
  ["Nomads", "nomad", "https://static.tibia.com/images/library/nomad.gif"],
  ["Norcferatu Heartlesses", "norcferatuheartless", "https://static.tibia.com/images/library/norcferatuheartless.gif"],
  ["Norcferatu Nightweavers", "norcferatunightweaver", "https://static.tibia.com/images/library/norcferatunightweaver.gif"],
  ["Northern Pikes", "northernpike", "https://static.tibia.com/images/library/northernpike.gif"],
  ["Novices Of The Cult", "cultnovice", "https://static.tibia.com/images/library/cultnovice.gif"],
  ["Noxious Ripptors", "noxiousripptor", "https://static.tibia.com/images/library/noxiousripptor.gif"],
  ["Nymphs", "nymph", "https://static.tibia.com/images/library/nymph.gif"],
  ["Ogre Brutes", "ogrebrute", "https://static.tibia.com/images/library/ogrebrute.gif"],
  ["Ogre Rowdies", "ogrerowdy", "https://static.tibia.com/images/library/ogrerowdy.gif"],
  ["Ogre Ruffians", "ogreruffian", "https://static.tibia.com/images/library/ogreruffian.gif"],
  ["Ogre Sages", "ogresage", "https://static.tibia.com/images/library/ogresage.gif"],
  ["Ogre Savages", "ogresavage", "https://static.tibia.com/images/library/ogresavage.gif"],
  ["Ogre Shamans", "ogreshaman", "https://static.tibia.com/images/library/ogreshaman.gif"],
  ["Omnivoras", "omnivora", "https://static.tibia.com/images/library/omnivora.gif"],
  ["Oozing Carcasses", "oozingcarcass", "https://static.tibia.com/images/library/oozingcarcass.gif"],
  ["Oozing Corpuses", "oozingcorpus", "https://static.tibia.com/images/library/oozingcorpus.gif"],
  ["Orc Berserkers", "orcberserker", "https://static.tibia.com/images/library/orcberserker.gif"],
  ["Orc Cult Fanatics", "orccultfanatic", "https://static.tibia.com/images/library/orccultfanatic.gif"],
  ["Orc Cult Inquisitors", "orccultinquisitor", "https://static.tibia.com/images/library/orccultinquisitor.gif"],
  ["Orc Cult Minions", "orccultminion", "https://static.tibia.com/images/library/orccultminion.gif"],
  ["Orc Cult Priests", "orccultpriest", "https://static.tibia.com/images/library/orccultpriest.gif"],
  ["Orc Cultists", "orccultist", "https://static.tibia.com/images/library/orccultist.gif"],
  ["Orc Leaders", "orcleader", "https://static.tibia.com/images/library/orcleader.gif"],
  ["Orc Marauders", "orcmarauder", "https://static.tibia.com/images/library/orcmarauder.gif"],
  ["Orc Riders", "orcrider", "https://static.tibia.com/images/library/orcrider.gif"],
  ["Orc Shamans", "orcshaman", "https://static.tibia.com/images/library/orcshaman.gif"],
  ["Orc Spearmen", "orcspearman", "https://static.tibia.com/images/library/orcspearman.gif"],
  ["Orc Warlords", "orcwarlord", "https://static.tibia.com/images/library/orcwarlord.gif"],
  ["Orc Warriors", "orcwarrior", "https://static.tibia.com/images/library/orcwarrior.gif"],
  ["Orclops Bloodbreakers", "norcferatuorclops", "https://static.tibia.com/images/library/norcferatuorclops.gif"],
  ["Orclops Doomhaulers", "orclops", "https://static.tibia.com/images/library/orclops.gif"],
  ["Orclops Ravagers", "orclopsravager", "https://static.tibia.com/images/library/orclopsravager.gif"],
  ["Orcs", "orc", "https://static.tibia.com/images/library/orc.gif"],
  ["Orewalkers", "orewalker", "https://static.tibia.com/images/library/orewalker.gif"],
  ["Paladin's Apparitions", "paladinsapparition", "https://static.tibia.com/images/library/paladinsapparition.gif"],
  ["Pandas", "panda", "https://static.tibia.com/images/library/panda.gif"],
  ["Parders", "parder", "https://static.tibia.com/images/library/parder.gif"],
  ["Parrots", "parrot", "https://static.tibia.com/images/library/parrot.gif"],
  ["Penguins", "penguin", "https://static.tibia.com/images/library/penguin.gif"],
  ["Phantasms", "phantasm", "https://static.tibia.com/images/library/phantasm.gif"],
  ["Pigeons", "pigeon", "https://static.tibia.com/images/library/pigeon.gif"],
  ["Pigs", "pig", "https://static.tibia.com/images/library/pig.gif"],
  ["Pirat Bombardiers", "piratbombardier", "https://static.tibia.com/images/library/piratbombardier.gif"],
  ["Pirat Cutthroats", "piratcutthroat", "https://static.tibia.com/images/library/piratcutthroat.gif"],
  ["Pirat Mates", "piratmate", "https://static.tibia.com/images/library/piratmate.gif"],
  ["Pirat Scoundrels", "piratscoundrel", "https://static.tibia.com/images/library/piratscoundrel.gif"],
  ["Pirate Buccaneers", "piratebuccaneer", "https://static.tibia.com/images/library/piratebuccaneer.gif"],
  ["Pirate Cooks", "cook", "https://static.tibia.com/images/library/cook.gif"],
  ["Pirate Corsairs", "piratecorsair", "https://static.tibia.com/images/library/piratecorsair.gif"],
  ["Pirate Cutthroats", "piratecutthroat", "https://static.tibia.com/images/library/piratecutthroat.gif"],
  ["Pirate Ghosts", "pirateghost", "https://static.tibia.com/images/library/pirateghost.gif"],
  ["Pirate Gunners", "gunner", "https://static.tibia.com/images/library/gunner.gif"],
  ["Pirate Marauders", "piratemarauder", "https://static.tibia.com/images/library/piratemarauder.gif"],
  ["Pirate Navigators", "navigator", "https://static.tibia.com/images/library/navigator.gif"],
  ["Pirate Quartermasters", "quartermaster", "https://static.tibia.com/images/library/quartermaster.gif"],
  ["Pirate Skeletons", "pirateskeleton", "https://static.tibia.com/images/library/pirateskeleton.gif"],
  ["Pixies", "pixie", "https://static.tibia.com/images/library/pixie.gif"],
  ["Plaguesmiths", "plaguesmith", "https://static.tibia.com/images/library/plaguesmith.gif"],
  ["Poachers", "poacher", "https://static.tibia.com/images/library/poacher.gif"],
  ["Poison Spiders", "poisonspider", "https://static.tibia.com/images/library/poisonspider.gif"],
  ["Poisonous Carnisylvans", "carnisylvanpoisonous", "https://static.tibia.com/images/library/carnisylvanpoisonous.gif"],
  ["Polar Bears", "polarbear", "https://static.tibia.com/images/library/polarbear.gif"],
  ["Pookas", "pooka", "https://static.tibia.com/images/library/pooka.gif"],
  ["Priestesses", "priestess", "https://static.tibia.com/images/library/priestess.gif"],
  ["Priestesses Of The Wild Sun", "priestessofthewildsun", "https://static.tibia.com/images/library/priestessofthewildsun.gif"],
  ["Putrid Mummies", "putridmummy", "https://static.tibia.com/images/library/putridmummy.gif"],
  ["Quara Constrictor Scouts", "quaraconstrictorscout", "https://static.tibia.com/images/library/quaraconstrictorscout.gif"],
  ["Quara Constrictors", "quaraconstrictor", "https://static.tibia.com/images/library/quaraconstrictor.gif"],
  ["Quara Hydromancer Scouts", "quarahydromancerscout", "https://static.tibia.com/images/library/quarahydromancerscout.gif"],
  ["Quara Hydromancers", "quarahydromancer", "https://static.tibia.com/images/library/quarahydromancer.gif"],
  ["Quara Looters", "quaralooter", "https://static.tibia.com/images/library/quaralooter.gif"],
  ["Quara Mantassin Scouts", "quaramantassinscout", "https://static.tibia.com/images/library/quaramantassinscout.gif"],
  ["Quara Mantassins", "quaramantassin", "https://static.tibia.com/images/library/quaramantassin.gif"],
  ["Quara Pincher Scouts", "quarapincherscout", "https://static.tibia.com/images/library/quarapincherscout.gif"],
  ["Quara Pinchers", "quarapincher", "https://static.tibia.com/images/library/quarapincher.gif"],
  ["Quara Plunderers", "quaraplunderer", "https://static.tibia.com/images/library/quaraplunderer.gif"],
  ["Quara Predator Scouts", "quarapredatorscout", "https://static.tibia.com/images/library/quarapredatorscout.gif"],
  ["Quara Predators", "quarapredator", "https://static.tibia.com/images/library/quarapredator.gif"],
  ["Quara Raiders", "quararaider", "https://static.tibia.com/images/library/quararaider.gif"],
  ["Rabbits", "rabbit", "https://static.tibia.com/images/library/rabbit.gif"],
  ["Rabid Wolves", "rabidwolf", "https://static.tibia.com/images/library/rabidwolf.gif"],
  ["Radiant Acolytes", "radiantacolyte", "https://static.tibia.com/images/library/radiantacolyte.gif"],
  ["Radiant Inquisitors", "radiantinquisitor", "https://static.tibia.com/images/library/radiantinquisitor.gif"],
  ["Radiant Paragons", "radiantparagon", "https://static.tibia.com/images/library/radiantparagon.gif"],
  ["Radiant Templars", "radianttemplar", "https://static.tibia.com/images/library/radianttemplar.gif"],
  ["Radiant Wardens", "radiantwarden", "https://static.tibia.com/images/library/radiantwarden.gif"],
  ["Radiant Zealots", "radiantzealot", "https://static.tibia.com/images/library/radiantzealot.gif"],
  ["Rage Squids", "ragingbrainsquid", "https://static.tibia.com/images/library/ragingbrainsquid.gif"],
  ["Ragged Rabid Wolves", "raggedrabidwolf", "https://static.tibia.com/images/library/raggedrabidwolf.gif"],
  ["Rats", "rat", "https://static.tibia.com/images/library/rat.gif"],
  ["Raubritter Chasteners", "raubritterchastener", "https://static.tibia.com/images/library/raubritterchastener.gif"],
  ["Raubritter Marksmen", "raubrittermarksman", "https://static.tibia.com/images/library/raubrittermarksman.gif"],
  ["Raubritter Skirmishers", "raubritterskirmisher", "https://static.tibia.com/images/library/raubritterskirmisher.gif"],
  ["Ravenous Lava Lurkers", "aggressivelavalurker", "https://static.tibia.com/images/library/aggressivelavalurker.gif"],
  ["Reality Reavers", "realityreaver", "https://static.tibia.com/images/library/realityreaver.gif"],
  ["Redeemed Souls", "redeemedsoul", "https://static.tibia.com/images/library/redeemedsoul.gif"],
  ["Renegade Knights", "renegadeknight", "https://static.tibia.com/images/library/renegadeknight.gif"],
  ["Retching Horrors", "retchinghorror", "https://static.tibia.com/images/library/retchinghorror.gif"],
  ["Rhindeer", "rhindeer", "https://static.tibia.com/images/library/rhindeer.gif"],
  ["Ripper Spectres", "ripperspectre", "https://static.tibia.com/images/library/ripperspectre.gif"],
  ["Roaming Dreads", "roamingdread", "https://static.tibia.com/images/library/roamingdread.gif"],
  ["Roaring Lions", "roaringlion", "https://static.tibia.com/images/library/roaringlion.gif"],
  ["Rootthing Amber Shapers", "rootthingambershaper", "https://static.tibia.com/images/library/rootthingambershaper.gif"],
  ["Rootthing Bug Trackers", "rootthingbugtracker", "https://static.tibia.com/images/library/rootthingbugtracker.gif"],
  ["Rootthing Nutshells", "rootthingnutshell", "https://static.tibia.com/images/library/rootthingnutshell.gif"],
  ["Rorcs", "rorc", "https://static.tibia.com/images/library/rorc.gif"],
  ["Rot Elementals", "rotelemental", "https://static.tibia.com/images/library/rotelemental.gif"],
  ["Rotten Golems", "rottengolem", "https://static.tibia.com/images/library/rottengolem.gif"],
  ["Rotten Man-maggots", "rottenmanmaggot", "https://static.tibia.com/images/library/rottenmanmaggot.gif"],
  ["Rotworms", "rotworm", "https://static.tibia.com/images/library/rotworm.gif"],
  ["Rustheap Golems", "rustheapgolem", "https://static.tibia.com/images/library/rustheapgolem.gif"],
  ["Sabreteeth", "sabretooth", "https://static.tibia.com/images/library/sabretooth.gif"],
  ["Salamanders", "salamander", "https://static.tibia.com/images/library/salamander.gif"],
  ["Sandcrawlers", "sandcrawler", "https://static.tibia.com/images/library/sandcrawler.gif"],
  ["Sandstone Scorpions", "sandstonescorpion", "https://static.tibia.com/images/library/sandstonescorpion.gif"],
  ["Scarabs", "scarab", "https://static.tibia.com/images/library/scarab.gif"],
  ["Scorpions", "scorpion", "https://static.tibia.com/images/library/scorpion.gif"],
  ["Sea Captains", "seacaptain", "https://static.tibia.com/images/library/seacaptain.gif"],
  ["Sea Serpents", "seaserpent", "https://static.tibia.com/images/library/seaserpent.gif"],
  ["Seacrest Serpents", "seacrest", "https://static.tibia.com/images/library/seacrest.gif"],
  ["Seagulls", "seagull", "https://static.tibia.com/images/library/seagull.gif"],
  ["Serpent Spawns", "serpentspawn", "https://static.tibia.com/images/library/serpentspawn.gif"],
  ["Shadow Pupils", "shadowpupil", "https://static.tibia.com/images/library/shadowpupil.gif"],
  ["Shaper Matriarches", "shapermatriarch", "https://static.tibia.com/images/library/shapermatriarch.gif"],
  ["Sharks", "shark", "https://static.tibia.com/images/library/shark.gif"],
  ["Sheep", "sheep", "https://static.tibia.com/images/library/sheep.gif"],
  ["Shell Drakes", "shelldrake", "https://static.tibia.com/images/library/shelldrake.gif"],
  ["Shock Heads", "shockhead", "https://static.tibia.com/images/library/shockhead.gif"],
  ["Shrieking Cry-stals", "shriekingcrystal", "https://static.tibia.com/images/library/shriekingcrystal.gif"],
  ["Sibangs", "sibang", "https://static.tibia.com/images/library/sibang.gif"],
  ["Sights Of Surrender", "sightofsurrender", "https://static.tibia.com/images/library/sightofsurrender.gif"],
  ["Silencers", "silencer", "https://static.tibia.com/images/library/silencer.gif"],
  ["Silver Rabbits", "silverrabbit", "https://static.tibia.com/images/library/silverrabbit.gif"],
  ["Silverfrost Sentinels", "silverfrostsentinel", "https://static.tibia.com/images/library/silverfrostsentinel.gif"],
  ["Sineater Inferniarches", "sineaterinferniarch", "https://static.tibia.com/images/library/sineaterinferniarch.gif"],
  ["Skeleton Elite Warriors", "skeletonelite", "https://static.tibia.com/images/library/skeletonelite.gif"],
  ["Skeleton Warriors", "skeletonwarrior", "https://static.tibia.com/images/library/skeletonwarrior.gif"],
  ["Skeletons", "skeleton", "https://static.tibia.com/images/library/skeleton.gif"],
  ["Skunks", "skunk", "https://static.tibia.com/images/library/skunk.gif"],
  ["Slimes", "slime", "https://static.tibia.com/images/library/slime.gif"],
  ["Slugs", "slug", "https://static.tibia.com/images/library/slug.gif"],
  ["Smugglers", "smuggler", "https://static.tibia.com/images/library/smuggler.gif"],
  ["Snakes", "snake", "https://static.tibia.com/images/library/snake.gif"],
  ["Sons Of Verminor", "sonofverminor", "https://static.tibia.com/images/library/sonofverminor.gif"],
  ["Sopping Carcasses", "soppingcarcass", "https://static.tibia.com/images/library/soppingcarcass.gif"],
  ["Sopping Corpuses", "soppingcorpus", "https://static.tibia.com/images/library/soppingcorpus.gif"],
  ["Sorcerer's Apparitions", "sorcerersapparition", "https://static.tibia.com/images/library/sorcerersapparition.gif"],
  ["Soul-broken Harbingers", "soulbrokenharbinger", "https://static.tibia.com/images/library/soulbrokenharbinger.gif"],
  ["Souleaters", "souleater", "https://static.tibia.com/images/library/souleater.gif"],
  ["Sparkions", "sparkion", "https://static.tibia.com/images/library/sparkion.gif"],
  ["Spectres", "spectre", "https://static.tibia.com/images/library/spectre.gif"],
  ["Spellreaper Inferniarches", "spellreaperinferniarch", "https://static.tibia.com/images/library/spellreaperinferniarch.gif"],
  ["Sphinxes", "sphinx", "https://static.tibia.com/images/library/sphinx.gif"],
  ["Spiders", "spider", "https://static.tibia.com/images/library/spider.gif"],
  ["Spidris", "spidris", "https://static.tibia.com/images/library/spidris.gif"],
  ["Spiky Carnivors", "spikycarnivor", "https://static.tibia.com/images/library/spikycarnivor.gif"],
  ["Spit Nettles", "spitnettle", "https://static.tibia.com/images/library/spitnettle.gif"],
  ["Spitters", "spitter", "https://static.tibia.com/images/library/spitter.gif"],
  ["Squid Wardens", "squidwarden", "https://static.tibia.com/images/library/squidwarden.gif"],
  ["Squirrels", "squirrel", "https://static.tibia.com/images/library/squirrel.gif"],
  ["Stabilizing Dread Intruders", "stabilizingdreadintruder", "https://static.tibia.com/images/library/stabilizingdreadintruder.gif"],
  ["Stabilizing Reality Reavers", "stabilizingrealityreaver", "https://static.tibia.com/images/library/stabilizingrealityreaver.gif"],
  ["Stags", "stag", "https://static.tibia.com/images/library/stag.gif"],
  ["Stalkers", "stalker", "https://static.tibia.com/images/library/stalker.gif"],
  ["Stalking Stalks", "stalkingstalk", "https://static.tibia.com/images/library/stalkingstalk.gif"],
  ["Stampors", "stampor", "https://static.tibia.com/images/library/stampor.gif"],
  ["Stone Devourers", "stonedevourer", "https://static.tibia.com/images/library/stonedevourer.gif"],
  ["Stone Golems", "stonegolem", "https://static.tibia.com/images/library/stonegolem.gif"],
  ["Stone Rhinos", "stonerhino", "https://static.tibia.com/images/library/stonerhino.gif"],
  ["Stonerefiners", "stonerefiner", "https://static.tibia.com/images/library/stonerefiner.gif"],
  ["Streaked Devourers", "streakeddevourer", "https://static.tibia.com/images/library/streakeddevourer.gif"],
  ["Sugar Cube Workers", "sugarcubeworker", "https://static.tibia.com/images/library/sugarcubeworker.gif"],
  ["Sugar Cubes", "sugarcube", "https://static.tibia.com/images/library/sugarcube.gif"],
  ["Sulphiders", "sulphider", "https://static.tibia.com/images/library/sulphider.gif"],
  ["Sulphur Spouters", "sulphurspouter", "https://static.tibia.com/images/library/sulphurspouter.gif"],
  ["Swamp Trolls", "swamptroll", "https://static.tibia.com/images/library/swamptroll.gif"],
  ["Swamplings", "swampling", "https://static.tibia.com/images/library/swampling.gif"],
  ["Swan Maidens", "swanmaiden", "https://static.tibia.com/images/library/swanmaiden.gif"],
  ["Swarmers", "swarmer", "https://static.tibia.com/images/library/swarmer.gif"],
  ["Tainted Souls", "taintedsoul", "https://static.tibia.com/images/library/taintedsoul.gif"],
  ["Tarantulas", "tarantula", "https://static.tibia.com/images/library/tarantula.gif"],
  ["Tarnished Spirits", "tarnishedspirit", "https://static.tibia.com/images/library/tarnishedspirit.gif"],
  ["Terramites", "terramite", "https://static.tibia.com/images/library/terramite.gif"],
  ["Terror Birds", "terrorbird", "https://static.tibia.com/images/library/terrorbird.gif"],
  ["Terrorsleeps", "terrorsleep", "https://static.tibia.com/images/library/terrorsleep.gif"],
  ["Thanatursuses", "thanatursus", "https://static.tibia.com/images/library/thanatursus.gif"],
  ["Thornback Tortoises", "thornbacktortoise", "https://static.tibia.com/images/library/thornbacktortoise.gif"],
  ["Tigers", "tiger", "https://static.tibia.com/images/library/tiger.gif"],
  ["Toads", "toad", "https://static.tibia.com/images/library/toad.gif"],
  ["Tortoises", "tortoise", "https://static.tibia.com/images/library/tortoise.gif"],
  ["Tremendous Tyrants", "tremendoustyrant", "https://static.tibia.com/images/library/tremendoustyrant.gif"],
  ["Troll Champions", "trollchampion", "https://static.tibia.com/images/library/trollchampion.gif"],
  ["Trolls", "troll", "https://static.tibia.com/images/library/troll.gif"],
  ["True Dawnfire Asuras", "truedawnfire", "https://static.tibia.com/images/library/truedawnfire.gif"],
  ["True Feverbloom Asuras", "feverbloomasura", "https://static.tibia.com/images/library/feverbloomasura.gif"],
  ["True Frost Flower Asuras", "truefrostflower", "https://static.tibia.com/images/library/truefrostflower.gif"],
  ["True Midnight Asuras", "truemidnight", "https://static.tibia.com/images/library/truemidnight.gif"],
  ["Truffle Cooks", "trufflecook", "https://static.tibia.com/images/library/trufflecook.gif"],
  ["Truffles", "truffle", "https://static.tibia.com/images/library/truffle.gif"],
  ["Tunnel Tyrants", "tunneltyrant", "https://static.tibia.com/images/library/tunneltyrant.gif"],
  ["Turbulent Elementals", "turbulentelemental", "https://static.tibia.com/images/library/turbulentelemental.gif"],
  ["Twisted Pookas", "twistedpooka", "https://static.tibia.com/images/library/twistedpooka.gif"],
  ["Twisted Shapers", "twistedshaper", "https://static.tibia.com/images/library/twistedshaper.gif"],
  ["Two-headed Turtles", "twoheadedturtle", "https://static.tibia.com/images/library/twoheadedturtle.gif"],
  ["Undead Cavebears", "undeadcavebear", "https://static.tibia.com/images/library/undeadcavebear.gif"],
  ["Undead Dragons", "undeaddragon", "https://static.tibia.com/images/library/undeaddragon.gif"],
  ["Undead Elite Gladiators", "undeadelitegladiator", "https://static.tibia.com/images/library/undeadelitegladiator.gif"],
  ["Undead Gladiators", "undeadgladiator", "https://static.tibia.com/images/library/undeadgladiator.gif"],
  ["Undertakers", "undertaker", "https://static.tibia.com/images/library/undertaker.gif"],
  ["Usurper Archers", "usurperarcher", "https://static.tibia.com/images/library/usurperarcher.gif"],
  ["Usurper Commanders", "usurpercommander", "https://static.tibia.com/images/library/usurpercommander.gif"],
  ["Usurper Knights", "usurperknight", "https://static.tibia.com/images/library/usurperknight.gif"],
  ["Usurper Warlocks", "usurperwarlock", "https://static.tibia.com/images/library/usurperwarlock.gif"],
  ["Valkyries", "valkyrie", "https://static.tibia.com/images/library/valkyrie.gif"],
  ["Vampire Brides", "vampirebride", "https://static.tibia.com/images/library/vampirebride.gif"],
  ["Vampire Viscounts", "vampireviscount", "https://static.tibia.com/images/library/vampireviscount.gif"],
  ["Vampires", "vampire", "https://static.tibia.com/images/library/vampire.gif"],
  ["Vargs", "varg", "https://static.tibia.com/images/library/varg.gif"],
  ["Varnished Diremaws", "varnisheddiremaw", "https://static.tibia.com/images/library/varnisheddiremaw.gif"],
  ["Venerable Girtablilus", "girtablilu", "https://static.tibia.com/images/library/girtablilu.gif"],
  ["Vexclaws", "vexclaw", "https://static.tibia.com/images/library/vexclaw.gif"],
  ["Vibrant Phantoms", "vibrantphantom", "https://static.tibia.com/images/library/vibrantphantom.gif"],
  ["Vicious Manbats", "viscountmanbat", "https://static.tibia.com/images/library/viscountmanbat.gif"],
  ["Vicious Squires", "vicioussquire", "https://static.tibia.com/images/library/vicioussquire.gif"],
  ["Vile Grandmasters", "vilegrandmaster", "https://static.tibia.com/images/library/vilegrandmaster.gif"],
  ["Vulcongras", "vulcongra", "https://static.tibia.com/images/library/vulcongra.gif"],
  ["Wailing Widows", "wailingwidow", "https://static.tibia.com/images/library/wailingwidow.gif"],
  ["Walkers", "walker", "https://static.tibia.com/images/library/walker.gif"],
  ["Walking Dreads", "walkingdread", "https://static.tibia.com/images/library/walkingdread.gif"],
  ["Walking Pillars", "walkingpillar", "https://static.tibia.com/images/library/walkingpillar.gif"],
  ["Wandering Pillars", "wanderingpillar", "https://static.tibia.com/images/library/wanderingpillar.gif"],
  ["War Golems", "wargolem", "https://static.tibia.com/images/library/wargolem.gif"],
  ["War Wolves", "warwolf", "https://static.tibia.com/images/library/warwolf.gif"],
  ["Wardragons", "wardragon", "https://static.tibia.com/images/library/wardragon.gif"],
  ["Warlocks", "warlock", "https://static.tibia.com/images/library/warlock.gif"],
  ["Waspoids", "waspoid", "https://static.tibia.com/images/library/waspoid.gif"],
  ["Wasps", "wasp", "https://static.tibia.com/images/library/wasp.gif"],
  ["Water Buffalos", "waterbuffalo", "https://static.tibia.com/images/library/waterbuffalo.gif"],
  ["Water Elementals", "waterelemental", "https://static.tibia.com/images/library/waterelemental.gif"],
  ["Weakened Frazzlemaws", "weakenedfrazzlemaw", "https://static.tibia.com/images/library/weakenedfrazzlemaw.gif"],
  ["Weepers", "weeper", "https://static.tibia.com/images/library/weeper.gif"],
  ["Werebadgers", "werebadger", "https://static.tibia.com/images/library/werebadger.gif"],
  ["Werebears", "werebear", "https://static.tibia.com/images/library/werebear.gif"],
  ["Wereboars", "wereboar", "https://static.tibia.com/images/library/wereboar.gif"],
  ["Werecrocodiles", "werecrocodile", "https://static.tibia.com/images/library/werecrocodile.gif"],
  ["Werefoxes", "werefox", "https://static.tibia.com/images/library/werefox.gif"],
  ["Werehyaena Shamans", "werehyaenashaman", "https://static.tibia.com/images/library/werehyaenashaman.gif"],
  ["Werehyaenas", "werehyaena", "https://static.tibia.com/images/library/werehyaena.gif"],
  ["Werelionesses", "werelioness", "https://static.tibia.com/images/library/werelioness.gif"],
  ["Werelions", "werelion", "https://static.tibia.com/images/library/werelion.gif"],
  ["Werepanthers", "werepanther", "https://static.tibia.com/images/library/werepanther.gif"],
  ["Weretigers", "weretiger", "https://static.tibia.com/images/library/weretiger.gif"],
  ["Werewolves", "werewolf", "https://static.tibia.com/images/library/werewolf.gif"],
  ["White Deer", "whitedeer", "https://static.tibia.com/images/library/whitedeer.gif"],
  ["White Lions", "whitelion", "https://static.tibia.com/images/library/whitelion.gif"],
  ["White Shades", "whiteshade", "https://static.tibia.com/images/library/whiteshade.gif"],
  ["White Tigers", "whitetiger", "https://static.tibia.com/images/library/whitetiger.gif"],
  ["White Weretigers", "whiteweretiger", "https://static.tibia.com/images/library/whiteweretiger.gif"],
  ["Wigglers", "wiggler", "https://static.tibia.com/images/library/wiggler.gif"],
  ["Wild Warriors", "wildwarrior", "https://static.tibia.com/images/library/wildwarrior.gif"],
  ["Wilting Leaf Golems", "wiltingleafgolem", "https://static.tibia.com/images/library/wiltingleafgolem.gif"],
  ["Winged Jaracals", "wingedjaracal", "https://static.tibia.com/images/library/wingedjaracal.gif"],
  ["Winter Wolves", "winterwolf", "https://static.tibia.com/images/library/winterwolf.gif"],
  ["Wisps", "wisp", "https://static.tibia.com/images/library/wisp.gif"],
  ["Witches", "witch", "https://static.tibia.com/images/library/witch.gif"],
  ["Wolves", "wolf", "https://static.tibia.com/images/library/wolf.gif"],
  ["Worker Golems", "workergolem", "https://static.tibia.com/images/library/workergolem.gif"],
  ["Worm Priestesses", "wormpriest", "https://static.tibia.com/images/library/wormpriest.gif"],
  ["Wyrms", "wyrm", "https://static.tibia.com/images/library/wyrm.gif"],
  ["Wyverns", "wyvern", "https://static.tibia.com/images/library/wyvern.gif"],
  ["Yielothax", "yielothax", "https://static.tibia.com/images/library/yielothax.gif"],
  ["Young Goannas", "younggoanna", "https://static.tibia.com/images/library/younggoanna.gif"],
  ["Young Sea Serpents", "youngseaserpent", "https://static.tibia.com/images/library/youngseaserpent.gif"],
  ["Zombies", "zombie", "https://static.tibia.com/images/library/zombie.gif"],
];
